typography_spectrum: 0.5494715326931328
color:
  brandStrength: 0.9587618857622147
  lightness: 0.5126965804956853
  saturation: 0.16025294130668044
  rhythmicContrast: 0.40894747665151954
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.1192172693554312
analytics:
  google: UA-83540909-1
author:
  name: Michael Pusateri
  email: michael@michaelpusateri.com
  url: michaelpusateri.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f749d4a3-95b3-4018-b7d1-631c3f239e5e.jpg
name: Michael Pusateri
navigation:
  - name: Work
    url: 'http://siepe.com'
    type: external
title: ''
description: CEO Siepe
